crypto-org-chain/chain-main

integration_tests/test_gov.py
integration_tests/test_staking.py
integration_tests/utils.py
pystarport/pystarport/cluster.py

Solution:
- test different vote options
- test change vote
- test inherit vote

Problem (fix #191): missing advanced gov integration tests

---

.github/workflows/goreleaser.yml
.goreleaser.yml

Solution: uncomment .goreleaser.yml and ci workflow for goreleaser

Problem: goreleaser.yml for brew is commented

---

Makefile
docker.nix
integration_tests/shell.nix
integration_tests/utils.py
pystarport/default.nix
shell.nix

Solution:
- find chain-maind on `PATH` when dev locally
- don't collect coverage report when test locally

Problem (fix #209): build chain-maind with nix-build too slow for local dev

---

app/app.go
default.nix
go.mod
go.sum
x/chainmain/client/cli/testnet.go
x/staking/client/cli/tx.go

Solution:
- upgrade to latest master

Problem (fix #210): lagged behind cosmos-sdk master version

---

Makefile
app/app.go
app/export.go
app/sim_test.go
default.nix
go.mod
go.sum
integration_tests/shell.nix
integration_tests/test_gov.py
integration_tests/test_staking.py
integration_tests/test_upgrade.py
integration_tests/upgrade-test.nix
integration_tests/upgrade-test.patch
integration_tests/utils.py
pystarport/pystarport/cluster.py
pystarport/pystarport/utils.py
x/chainmain/module.go

Solution:
- upgrade cosmos-sdk for the gov flag name change
- test cosmovisor
- setup cosmovisor, and check upgrade is done transparently
- test manual upgrade
- check when upgrade planed, node quits and wrote upgrade-info.json
- replace with patched binary and check it works

Problem (fix #215): no integration tests for upgrade

---

integration_tests/test_reward.py

Solution: change the range of assert

Problem: test_reward integration test fail occationally (fix #239)

---

app/app.go
cmd/chain-maind/app/app.go
default.nix
go.mod
go.sum
integration_tests/test_gov.py

Solution:
- upgrade cosmos-sdk for the fix

Problem: tally calculation fix is not used

---

integration_tests/test_upgrade.py
integration_tests/utils.py
pystarport/pystarport/cluster.py

Solution:
- add a normal cancel-software-upgrade test case

Problem (fix #234): software upgrade cancellation is not tested

---

default.nix

Solution:
- add testnet option

Problem: default.nix don't build testnet binary

---

default.nix

Solution:
- add network argument in nix file

Problem: can't build v0.7.0-rc0 testnet binary in nix

---

cmd/chain-maind/app/app.go
integration_tests/test_basic.py
pystarport/pystarport/cluster.py

Solution:
- enable snapshotting in chain-maind
- support create node with statesync enabled
- add a simple test verify it works

Problem (fix #233): statesync not tested

---

.flake8
.golangci.yml
Makefile
default.nix
integration_tests/poetry.lock
integration_tests/pyproject.toml
integration_tests/test_grpc.py
makeproto.sh
pystarport/pystarport/__init__.py
pystarport/pystarport/cluster.py
pystarport/pystarport/convert.sh
pystarport/pystarport/default.nix
pystarport/pystarport/ports.py
pystarport/pystarport/proto_python/grpc_util.py

Solution: add grpc query, tx broadcast integration test
generate proto+grpc code on the fly

Problem: missing grpc integration test (fix #194)

---

.github/workflows/build.yml
.github/workflows/codecov.yml
.github/workflows/goreleaser.yml
nix/sources.json

Solution: (Fix: #262) Update to 1.15.5

Problem: vulnerable version Golang is used

---

.github/workflows/build.yml
.github/workflows/lint.yml
.github/workflows/nix.yml
Makefile
default.nix
integration_tests/poetry.lock
integration_tests/pyproject.toml
pystarport/default.nix
pystarport/pystarport/cluster.py

The main reason for this change is that `mkShell` is not buildable, so we can't copy it around, make it into normal package will be more flexible. like work with scripts like [this](https://freux.fr/posts/remoteshell.html).
Solution:
- change nix shell to env package, and entry point script to run
integration tests

Problem (fixes #264): can't run integration tests in remote machine easily

---

nix/sources.json

https://github.com/NixOS/nixpkgs/blob/dd1b7e377f6d77ddee4ab84be11173d3566d6a18/pkgs/development/compilers/go/1.15.nix#L39
https://github.com/NixOS/nixpkgs/blob/1491bab2b1113e745f107a36c7b81f89aed8cf1c/pkgs/development/compilers/go/1.15.nix#L39
Solution:
- update with `niv update nixpkgs -b master`

Problem: golang used in nix is not 1.15.5

---

pystarport/pystarport/cli.py
pystarport/pystarport/cluster.py
x/chainmain/client/cli/genaccounts.go

Solution:
- use unix timestamp in vesting time parameter
- make our chain compatible with that
So with this `config.yaml`:
```yaml
chainmaind:
validators:
- coins: 1000000stake
staked: 1000000stake
accounts:
- name: launch
coins: 100atom
```
You can run the `simd` in cosmos-sdk repo:
```
$ pystarport --cmd ./simd serve
```

Problem: pystarport don't work with other cosmos-sdk chain binary

---

integration_tests/poetry.lock
integration_tests/pyproject.toml
integration_tests/test_sign_offline.py
pystarport/pystarport/cluster.py
pystarport/pystarport/proto_python/api_util.py
pystarport/pystarport/proto_python/grpc_util.py

solution: add an integration test using cryptopy to sign transaction offline

Problem fix(#219): missing python wallet and tx signing framework

---

default.nix
examples/testnet.yaml
examples/testnet_genesis.json
integration_tests/test_upgrade.py
integration_tests/utils.py
pystarport/pystarport/cli.py
pystarport/pystarport/cluster.py

Solution:
- support join existing network by specify genesis file and peers
- support recover from existing mnemonic and consensus key
Two use cases for this feature:
- connect testnet conveniently, one just run:
`pystarport --cmd ./rc2/bin/chain-maind serve --config examples/testnet.yaml`
it'll sync the testnet with fresh consensus key and wallet.
the statesync feature still need to be enabled manually though.
- run a local devnet with some pre-existing genesis file, you can recover from existing validator by set mnemonic and consensus_key.

Problem: pystarport don't support join existing network

---

integration_tests/configs/default.yaml
integration_tests/test_staking.py
pystarport/pystarport/cluster.py

Problem (fix #292): no integration tests for min-self-delegation

---

app/app.go
cmd/chain-maind/app/app.go
cmd/chain-maind/main.go
cmd/chain-maind/main_test.go
integration_tests/configs/staking.yaml
integration_tests/test_gov.py
integration_tests/test_slashing.py
integration_tests/test_staking.py
pystarport/pystarport/cluster.py
x/chainmain/client/cli/genaccounts.go

Solution:
- use a separate cluster config for this test case
- make it more stable by not depend on order of validators response
- stablise other integration tests
- use builtin `Execute`, which add new log_level flag, register tmservice grpc gateway (follow the change in cosmos-sdk rc5)

Problem: test_min_self_delegate don't work in recent version

---

.github/workflows/nix.yml
default.nix
scripts/chain-utils.nix

- write a script with nix packaged together with binary
- print-systemd-config
We can put something like this into docs for user:
setup nix and binary cache, then:
```
$ nix-env -iA chain-utils-testnet -f https://github.com/crypto-com/chain-main/archive/***.tar.gz
$ MONIKER=testnode init-node
$ chain-maind start
... state sync enabled
```
setup systemd:
```
$ print-systemd-config > /etc/systemd/system/chain-maind.service
$ sudo systemctl start chain-maind
```

Problem: no one-key testnet node setup instruction

---

scripts/chain-utils.nix

Solution
- update parameters
we can merge this after new testnet more finalized.

Problem: testnet configurations are not update to testnet-croeseid-2

---

x/chainmain/types/genesis.go
x/supply/types/genesis.go

Solution: Added a comment explaining the reason for not performing any validations. Fixes #333.

Problem: Empty genesis validation function

---

default.nix
integration_tests/test_basic.py
integration_tests/test_upgrade.py
integration_tests/utils.py

Problem (fix #325): integration test failure

---

default.nix
examples/ibc.yaml
integration_tests/configs/ibc.yaml
integration_tests/conftest.py
integration_tests/test_hardware_wallet.py
integration_tests/test_ibc.py
integration_tests/test_multisig.py
integration_tests/test_slashing.py
integration_tests/test_staking.py
integration_tests/test_upgrade.py
integration_tests/utils.py
nix/default.nix
nix/sources.json

Solution:
- update relayer
- update integration test to auto-generate client/channel/connection id
- select unique ports automatically

Problem (fix #342): ibc integration tests don't work in recent version

---

default.nix
go.mod
go.sum
nix/sources.json
pystarport/pystarport/cluster.py
pystarport/pystarport/convert.sh

Solution: bumped the dependency to rc7 + removed the double amount
integration tests workaround

Problem: codebase is not using the latest SDK pre-release

---

config/prefix_crossfire.go
config/prefix_testnet.go

Solution: added another network build configuration option

Problem: crossfire config not possible (fixes #350)

---

CHANGELOG.md
default.nix
go.mod
go.sum
nix/sources.json
pystarport/pystarport/convert.sh

Solution: upgraded the dependency from a release candidate to v0.40 release

Problem: final 0.40 SDK release not used

---

nix/default.nix
nix/sources.json

Solution:
- Since related PRs are merged, we change to use master branch

Problem: relayer master is not used

---

scripts/chain-utils.nix

Solution:
- change testnet tag used in chain-utils script

Problem: v0.8.0-croeseid is not used in nix script

---

x/subscription/spec/01_concepts.md
x/subscription/spec/02_state.md
x/subscription/spec/03_messages.md
x/subscription/spec/04_events.md
x/subscription/spec/05_params.md
x/subscription/spec/06_begin_block.md
x/subscription/spec/README.md

Solution:
- add one
TODO: change to pseudocode to Golang after impl.

Problem (fix #294): no spec for subscriptions module

---

.goreleaser.yml

Solution: add bin to wrap binary

Problem: (fix #369) goreleaser tarballs aren't compatible with the current cosmovisor

---

.github/workflows/audit.yml
.github/workflows/build.yml
.github/workflows/codecov.yml
.github/workflows/goreleaser.yml
.github/workflows/lint.yml
.github/workflows/nix.yml

Solution:
- add one, prepare for another pr

Problem: github action don't enable submodule support

---

x/subscription/spec/01_concepts.md
x/subscription/spec/02_state.md
x/subscription/spec/03_messages.md
x/subscription/spec/05_params.md
x/subscription/spec/06_begin_block.md

extracted from https://github.com/crypto-org-chain/chain-main/pull/381
Solution:
- update spec extracted from implementation pr

Problem: subscription spec is not revised for implementation

---

nix/default.nix

Solution:
- update to correct one

Problem: cosmovisor's vendorSha256 is wrong

---

Dockerfile

Solution: add git module update command to dockerfile

Problem: (fix #401)missing git submodule inside dockerfile

---

cmd/chain-maind/app/app.go
default.nix
go.mod
go.sum

Use google.renameio.WriteFile to achieve the file update atomically.

Problem: genesis file is updated non-atomically (fixes #398)

---

doc/architecture/README.md
doc/architecture/adr-001.md

Solution: added a proposal to include the CosmWasm module

Problem: no lightweight extensibility approach (fixes #392)

---

integration_tests/test_upgrade.py
pystarport/pystarport/cosmoscli.py

- Chain export test based on #289
- The test case do export, override genesis file, and reset data
- Check the cluster can execute well, no consensus break
Note:
- The test is not able to test the genesis update / the state export between two binary versions.

Problem: manual export test

---

.github/workflows/build.yml
.github/workflows/codecov.yml
.github/workflows/goreleaser.yml
go.mod
nix/sources.json

Solution: upgrade to golang 1.16 , which supports apple m1 officially

Problem: missing upgrade to golang 1.16 (fix #416)

---

integration_tests/configs/byzantine.yaml
integration_tests/test_byzantine.py
pystarport/pystarport/cluster.py

- create 3 validator nodes, keep node0 has more than  2/3 voting power
- stop node2, and copy node1's validator key file to node2
- start node2, waiting for node1/node2 jailed
- check the tokens after node slashed and byzantine error

Problem: no Byzantine integration test(fix #365) 

---

nix/default.nix
nix/sources.json
pystarport/pystarport/cluster.py
pystarport/pystarport/cosmoscli.py

Solution:
- Support more customization in config file
- Update relayer to recent version which has fixed some bugs
An example configuration that setup ibc with testnet chain-maind and wasmd locally:
```
ibc-0:
cmd: ./build/chain-maind
account-prefix: tcro
coin-type: 1
validators:
- coins: 10tcro
staked: 10tcro
base_port: 26650
- coins: 10tcro
staked: 10tcro
accounts:
- name: relayer
coins: 100tcro
genesis:
app_state:
transfer:
params:
receive_enabled: true
send_enabled: true
ibc-1:
cmd: ../wasmd/build/wasmd
account-prefix: wasm
coin-type: 118
gas-prices: 0.0ucosm
validators:
- coins: 1000000000ustake,1000000000ucosm
staked: 1000000000ustake
base_port: 26750
- coins: 1000000000ustake,1000000000ucosm
staked: 1000000000ustake
base_port: 26760
accounts:
- name: relayer
coins: 1000000000ucosm …
```

Problem: pystarport can't run ibc devnets with different configurations

---

.github/workflows/build.yml
Makefile
cmd/chain-maind/app/app.go
cmd/chain-maind/app/appunix.go
cmd/chain-maind/app/appwin.go
go.sum

Solution: use ioutil.WriteFile,
file atomicity is done via file level.

Problem: chain-main can't be built for windows (fix #406)

---

integration_tests/test_hardware_wallet.py
pystarport/pystarport/cluster.py
pystarport/pystarport/cosmoscli.py

test many many ledger name formats

Problem:missing integration test of wallet-name in ledger(#255)

---

CHANGELOG.md
default.nix
go.mod
go.sum

Solution: bumped the dependency to Cosmos SDK v0.42.3

Problem: not using the latest SDK release

---

default.nix
scripts/chain-utils.nix

Solution:
- add mainnet option
Test:
```
$ nix-build -A chain-utils-mainnet
$ CHAINHOME=./data MONIKER=testnode ./result/bin/init-node
$ ./result/bin/chain-maind start --home ./data
```

Problem: chain-utils is not updated for mainnet

---

integration_tests/README.md
readme.md

Update the readme files for the macOS setup.

Update documents for the macOS (fixes #407)

---

cmd/chain-maind/app/app.go
x/chainmain/client/cli/query.go

add a new query command `txs-all` to query all the events transactions

Problem: no aggregated TX history command(#285)

---

default.nix
gomod2nix.toml
nix/default.nix
nix/sources.json

Solution:
- migrate from buildGoModule to gomod2nix
merge after https://github.com/tweag/gomod2nix/pull/9 is merged.

Problem: gomod2nix is not used

---

x/subscription/keeper/keeper.go

Problem: Typo in method name

---

x/subscription/keeper/keeper.go
x/subscription/spec/01_concepts.md
x/subscription/types/calendar_test.go
x/subscription/types/errors.go
x/subscription/types/params.go

Problem: Typos in subscription module

---

nix/default.nix
nix/sources.json
pystarport/pystarport/cluster.py
pystarport/pystarport/cosmoscli.py

Solution: cherry-picked 5d389779a9df582d62be0e6eceeccd0cf3e5abc0

Problem: nix flow fails on release/v1

---

integration_tests/configs/subscription.yaml
integration_tests/test_subscription.py
pystarport/pystarport/cluster.py
pystarport/pystarport/cosmoscli.py

Solution:
- Support the minimum-gas-prices in config
- Change subscription test setup to use non-zero gas fee
Prepare for more sophisticated integration tests for gas fees in subscription module.

Problem: pystarport don't support minimal-gas-price

---

readme.md

Proposal for crypto-org-chain/chain-main#474
I hereby certify that my contribution is in accordance with the Developer Certificate of Origin (https://developercertificate.org/).

Fixed Build Status Badge link.

---

CONTRIBUTING.md

Added link to new issue selection. Proposal to fix crypto-org-chain/chain-main#472
"I hereby certify that my contribution is in accordance with the Developer Certificate of Origin (https://developercertificate.org/)."

Fixed link to new issue selection at Contributing documentation

---

x/subscription/types/cronspec_bench_test.go
x/subscription/types/cronspec_test.go

Solution:
- benchmark several cases
- also added several unit test cases and format some code
result on my mac:
```
goos: darwin
goarch: amd64
pkg: github.com/crypto-org-chain/chain-main/v1/x/subscription/types
cpu: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
BenchmarkRoundUpYearly
BenchmarkRoundUpYearly-16      	 6438783	       178.3 ns/op
BenchmarkRoundUpMonthly
BenchmarkRoundUpMonthly-16     	 6354093	       195.8 ns/op
BenchmarkRoundUpWeekly
BenchmarkRoundUpWeekly-16      	 4748344	       249.1 ns/op
BenchmarkRoundUpLeapYear
BenchmarkRoundUpLeapYear-16    	16125798	        74.17 ns/op
BenchmarkRoundUpOverlap
BenchmarkRoundUpOverlap-16     	 4636618	       259.1 ns/op
BenchmarkCompile
BenchmarkCompile-16            	 2755452	       429.5 ns/op
BenchmarkCountPeriods …
```

Problem (fix #459): RoundUp in subscription module is not benchmarked

---

integration_tests/poetry.lock
integration_tests/test_sign_offline.py

Solution:
- do poetry update, and replace cryptopy with chainlibpy

Problem: cryptopy is not changed to chainlibpy completely

---

x/subscription/keeper/keeper.go
x/subscription/types/cronspec.go
x/subscription/types/cronspec_bench_test.go
x/subscription/types/cronspec_test.go

Solution:
- Consume gas incrementally, avoid attack vulnerability

Problem (fix #460): CountPeriod function in subscription module is slow

---

integration_tests/test_basic.py
integration_tests/test_subscription.py
x/subscription/abci.go
x/subscription/keeper/keeper.go
x/subscription/spec/05_params.md
x/subscription/types/params.go

Solution:
- estimate one based on default gas config

Problem (fix #471): the default GasPerCollection value is arbitrary

---

doc/architecture/README.md
doc/architecture/adr-002.md

Solution: wrote up ADR with the proposed CosmWasm replacement approach

Problem: potential problems with the subscription module (fixes #481)

---

.github/workflows/buildwin.yml
makewin.bat

Solution: add compiling script for windows
needs mingw64 beforehand for native compile

Problem: missing Makefile equivalent for windows (fix #443)

---

.github/workflows/buildwin.yml

Problem: github action name spelling is incorrect (fix #487)

---

doc/architecture/adr-001.md

Solution: updated the decision with more technical consequences
given the current state of CosmWasm.

Problem: missing consequences in ADR-001 (fixes #492)

---

.github/workflows/build.yml
.github/workflows/buildwin.yml

Solution: remove windows build steps from build.yml and simulation

Problem: (fix #517)windows build step still exists in build.yml

---

doc/architecture/README.md
doc/architecture/adr-001.md
doc/architecture/adr-003.md

Solution: wrote up ADR to propose a smaller scope upgrade

Problem: diverging milestones of external dependencies

---

x/nft/spec/01_state.md
x/nft/spec/02_messages.md

Solution: Add stricter constraints in NFT module specifications. Related to #520.

Problem: Vendored NFT module's permissions are too lax

---

integration_tests/conftest.py
integration_tests/test_byzantine.py
integration_tests/test_hardware_wallet.py
integration_tests/test_ibc.py
integration_tests/test_slashing.py
integration_tests/test_staking.py
integration_tests/test_upgrade.py
integration_tests/utils.py

Solution:
- upgrade test should init node with old version rather than the new one

Problem: upgrade integration tests don't init with old version

---

default.nix
integration_tests/test_ibc.py
integration_tests/test_staking.py
nix/default.nix
nix/sources.json
pystarport/pystarport/cluster.py

fixes #508
Solution:
- change to hermes(ibc-rs)
- migrate pystarport serve
- migrate integration test
> test case `test_update_chain_id` is ignored, because I checked that after node restart, the chain-id in rpc response don't change, the chain-id don't take effect in chain state, probably need to unsafe-reset-all.

Problem: golang relayer is deprecated and don't work with new cosmos-sdk

---

.golangci.yml
x/nft/keeper/denom.go
x/nft/types/common_test.go
x/nft/types/denom.go
x/nft/types/keys.go
x/nft/types/nft.go

Solution: Removed deprecated linters and added recommended replacements. Fixes #530.

Problem: Use of deprecated golangci-lint linters

---

pystarport/LICENSE
pystarport/README.md
pystarport/poetry.lock
pystarport/pyproject.toml

Fixes #540
Solution:
- distribute pystarport to pypi
- update readme and add ibc section to it

Problem: pystarport is not pip installable

---

integration_tests/test_nft.py
integration_tests/test_upgrade.py
pystarport/pystarport/cluster.py
pystarport/pystarport/cosmoscli.py
pystarport/pystarport/utils.py

add nft integration test
create
mint
transfer
edit
burn

Solution: add integration test for nft (fix #528)

---

CHANGELOG.md
app/app.go

Solution: a small update for the mainnet binary pre-release

Problem: changelog not up to date

---

CHANGELOG.md

Solution: updated the changelog with an entry to v2.0.1

Problem: changelog is not up to date

---

Makefile
MakefileDoc

Solution: add make.sh for submodule update

Problem: no submodule update in Makefile (fix #544)

---

integration_tests/configs/ibc.yaml
integration_tests/test_ibc_extended.py

Solution: add integration test (fix  #504)

Problem: missing extended IBC integration tests (fix #504)

---

Makefile
MakefileDoc
scripts/protocgen

Solution: remove proto lint
and tidy up

Problem: make proto-all not working (fix #562)

---

readme.md

Solution: add pystarport quick start guide

Problem: missing docs for pystarport setup with PyPI (fix #567)

---

.github/workflows/nix.yml
Makefile
default.nix
integration_tests/conftest.py
integration_tests/test_basic.py
integration_tests/test_byzantine.py
integration_tests/test_gov.py
integration_tests/test_ibc.py
integration_tests/test_ibc_extended.py
integration_tests/test_multisig.py
integration_tests/test_nft.py
integration_tests/test_reward.py
integration_tests/test_sign_offline.py
integration_tests/test_staking.py
integration_tests/test_upgrade.py

Solution: use concurrent jobs using pytest.marks

Problem: integration test takes too long time to complete (fix #489)

---

CHANGELOG.md
app/app.go
app/params/encoding.go
app/types.go
cmd/chain-maind/app/app.go
go.mod
go.sum
gomod2nix.toml
x/chainmain/module.go
x/nft/keeper/keeper_test.go
x/nft/keeper/querier.go
x/nft/module.go
x/nft/types/codec.go
x/supply/module.go

Solution: bumped the Cosmos SDK version, updated the changelog + removed
the broadcast mode hardcoding in CLI (as it can now be configured in app.toml)

Problem: the latest SDK is not used

---

CHANGELOG.md
go.mod
go.sum
gomod2nix.toml

Solution: bumped SDK version to v0.42.7 which backported the fix

Problem: ReadUpgradeInfoFromDisk cause panic on startup occasionally (fixes #589)

---

.goreleaser.yml

Closes: #602
changed ServerName and ClientName to AppName.

Problem: goreleaser config file set wrong version field names

---

readme.md

Update the badges typos present in the README.
---
This PR is in accordance with the [Developer's Certificate of Origin](https://github.com/crypto-org-chain/chain-main/blob/master/CONTRIBUTING.md#developer-certificate-of-origin). (There is a typo in the issue template for that link btw).

Update badges typos

---

integration_tests/configs/ibc_channel_genesis.yaml
integration_tests/test_ibc_channel_genesis.py

Solution:
Add ibc channel config and connection config in genesis file, use hermes to create client on two chains.
Test whether transactions between two chains generate correct account balance and number of transactions
Fix #573

Problem: setup ibc channel in genesis is not tested (Fix #573)

---

integration_tests/configs/ibc_channel_genesis.yaml
integration_tests/test_ibc_channel_genesis.py
integration_tests/utils.py

Solution:
- follow up on the ibc genesis integration tests, to show that one can
pre-compute the ibc token denomination and allocate them in the genesis.

Problem: allocate ibc tokens in genesis is not tested

---

go.mod
go.sum
gomod2nix.toml

Solution: upgraded the cosmos sdk and ibc-go dependencies

Problem: final release of SDK 0.43.0 is not used

---

CHANGELOG.md

Solution: added an entry for the latest testnet binaries

Problem: changelog not updated

---

CHANGELOG.md

Solution: updated an entry for v3.0.0

Problem: changelog not updated for v3 release

---

integration_tests/test_feegrant.py
integration_tests/utils.py

Solution:
Wait for latest block time to pass transaction block time plus grant period, instead of sleeping for the grant period amount of time
Fix #626

Problem: test_periodic_fee_allowance occasionally fails on GH Actions (Fix #626)

---

.github/workflows/build.yml
.github/workflows/buildwin.yml
.github/workflows/codecov.yml
.github/workflows/goreleaser.yml
Makefile
go.mod

Problem: golang-cross 1.17 is not yet on dockerhub

---

.github/workflows/build.yml
.github/workflows/buildwin.yml
.github/workflows/codecov.yml
.github/workflows/goreleaser.yml
CHANGELOG.md
Makefile
app/app.go
go.mod
go.sum
gomod2nix.toml
integration_tests/test_sign_offline.py
integration_tests/test_upgrade.py

Solution: added a custom empty upgrade handler
to upgrade from 0.43 to 0.44

Problem: testnet-croeseid-4 started on 0.43 

---

.github/workflows/nix.yml
integration_tests/conftest.py
integration_tests/test_authz.py
integration_tests/test_byzantine.py
integration_tests/test_hardware_wallet.py
integration_tests/test_ibc.py
integration_tests/test_ibc_channel_genesis.py
integration_tests/test_ibc_extended.py
integration_tests/test_slashing.py
integration_tests/test_staking.py
integration_tests/test_upgrade.py
integration_tests/test_vesting_staking.py
integration_tests/utils.py

Solution:
Upload data directory as artifact upon test failure
Fix #639

Problem: integration test data directory in CI is not accessible for debugging purpose (Fix #639)

---

CHANGELOG.md
go.mod
go.sum
gomod2nix.toml

Solution: changed the version from a custom fork to the upstream release

Problem: upstream SDK release not used

---

doc/architecture/adr-004.md

Solution: Added a draft ADR for transition

Problem: Missing ADR draft for NFT transition to the SDK module

---

CHANGELOG.md
NOTICE
app/app.go

Solution: added the double-migration workaround
as per https://github.com/cosmos/gaia/pull/1077/files

Problem: vesting accounts may be broken post-upgrade

---

go.mod
go.sum
gomod2nix.toml

Solution: bumped ibc-go to 2.0.1

Problem: the lastest ibc-go v2 is not used

---

go.mod
go.sum
gomod2nix.toml

Solution: bumped the ibc-go dependency to 2.0.2

Problem: incorrect module name in OnChanOpenInit events

---

x/nft/spec/02_messages.md

Solution:
recipiet -> recipient

Problem: Typo in nft message spec (#692)

---

.github/workflows/nix.yml
Makefile
integration_tests/poetry.lock
integration_tests/pyproject.toml

Solution:
- update github actions and fix nix run commands

Problem: nix flow in release/v1 fails with nix 2.4

---

Makefile
cmd/chain-maind/app/app.go
go.mod
go.sum
gomod2nix.toml
readme.md

Solution: add rocksdb build support

Problem: missing rocksdb build support in Makefile

---

doc/architecture/README.md
doc/architecture/adr-004.md

Solution: Added backwards incompatible changes in ADR-004 and changed its status to `Proposed`

Problem: ADR-004 does not clarify backwards incompatible changes

---

doc/architecture/README.md
doc/architecture/adr-005.md

Problem: Missing ADR for deprecation of `x/supply` module

---

CHANGELOG.md
go.mod
go.sum
gomod2nix.toml

Solution: Upgrade `ibc-go` to `v3.0.0`

Problem: `ibc-go` is not upgraded to latest version

---

.gitignore
CHANGELOG.md
go.mod
go.sum
gomod2nix.toml

Solution: Upgraded `cosmos-sdk` version

Problem: `cosmos-sdk` is not upgraded to `v0.45.2`

---

CHANGELOG.md

Solution: Added changelog entry

Problem: Missing changelog entry for interchain accounts

---

CHANGELOG.md
go.mod
go.sum
gomod2nix.toml

Solution: Upgraded cosmos-sdk to v0.45.3

Problem: Cosmos SDK version is not upgraded to latest

---

CHANGELOG.md

Solution: Added all the unreleased changes to v4.0.0-alpha1

Problem: Changelog is not updated for v4.0.0-alpha1

---

app/app.go

Solution: Temporarily disable fee middleware for ICA keepers. Fixes #766.

Problem: ICA test fails on `master` branch

---

.goreleaser.yml

Solution: Changed the build flags in testnet branch

Problem: Cannot build testnet binaries in CI

---

.goreleaser.yml

Problem: unnecessary archive name suffix

---

app/ante.go
app/app.go

Closes: #782
Solution: add ibcante.AnteHandler

Problem: ibc ante handler is not added to the ante pipeline

---

app/app.go
integration_tests/test_upgrade.py

Solution: Added an upgrade handler. Fixes #785.

Problem: Missing upgrade handler for wasmd

---

CHANGELOG.md

Problem: Changelog is not updated

---

.github/workflows/build.yml

Solution:
- use team verification for issue_comment workflow
- use go install instead of go get

Problem: simulations installation fails (fix #808 and #797)

---

.github/workflows/build.yml

Problem: wrong permission for build.yml to comment pr (fix #813)

---

app/app.go

Solution: Cherry pick fee middleware fix

Problem: `release/v4-croeseid` branch is not up-to-date

---

go.mod
go.sum
gomod2nix.toml

Solution: Upgrade `ibc-go` to `v4.0.0`

Problem: `ibc-go` is not upgraded to `v4.0.0`

---

.github/workflows/build.yml

Solution: increase the timeout minutes

Problem: simulations build times out on a PR

---

app/app.go
integration_tests/test_group.py

Solution: Added `x/group` with integration tests

Problem: `x/group` module not added and tested

---

integration_tests/configs/ica.yaml
integration_tests/poetry.lock
integration_tests/pyproject.toml
integration_tests/test_upgrade.py
nix/testenv.nix

Problem: recent version of pystarport is not used

---

default.nix
gomod2nix.toml
nix/sources.json

Problem: gomod2nix used in v3 is too old

---

.github/workflows/goreleaser.yml

Solution: added the additional required permissions

Problem: goreleaser flow fails on release/v3

---

.github/workflows/audit.yml

Solution: replaced Go Nancy with govulncheck that checks based
on transitively called functions (ref: https://go.dev/blog/vuln )

Problem: known vulnerabilities according to Go Nancy's scan (fixes #784)

---

.github/workflows/gosec.yml
.github/workflows/semgrep.yml

Solution: added semgrep and gosec

Problem: missing additional static analysis scans

---

.github/workflows/staticmajor.yml

Solution: added a CI static analysis for resource leaks

Problem: potential resource leaks are not checked

---

CHANGELOG.md
cmd/chain-maind/app/app.go
go.mod
go.sum
gomod2nix.toml

Solution:
- add flag to disable iavl fast node.

Problem: slow iavl fastnode migration is not optional

---

CHANGELOG.md
cmd/chain-maind/app/app.go

Solution:
- set to app in root cmd

Problem: iavl-disable-fastnode don't have effect

---

Makefile
cmd/chain-maind/app/app.go
readme.md

Solution: backport rocksdb build support

Problem: rocksdb build is not support in v3

---

.github/workflows/semgrep.yml

Problem: semgrep results are not uploaded

---

.github/workflows/audit.yml
.github/workflows/build.yml
.github/workflows/buildwin.yml
.github/workflows/codecov.yml
.github/workflows/codeql-analysis.yml
.github/workflows/goreleaser.yml
.github/workflows/lint.yml
Makefile

Solution: upgrade to go 1.19.4

Problem: govuln issue

---

CHANGELOG.md
go.mod
go.sum
gomod2nix.toml

Solution: upgraded to ibc-go 5.2.0

Problem: discontinued ibc-go version

---

CODE_OF_CONDUCT.md
readme.md

Fix: typos

---

.github/workflows/build.yml

Solution:
- allow commit sha after /runsim when it is from third party pr

Problem: build.yml doesn't enforce fix commit for third party pr for /runsim

---

.github/workflows/codeql-analysis.yml

Solution: updated to the main query repository

Problem: codeql-go is deprecated

---

.codecov.yml
.github/workflows/audit.yml
.github/workflows/build.yml
.github/workflows/buildwin.yml
.github/workflows/codeql-analysis.yml
.github/workflows/gosec.yml
.github/workflows/lint.yml
.github/workflows/nix.yml
.github/workflows/semgrep.yml
.github/workflows/staticmajor.yml

Solution: add ignore for irrelevant paths; upload results from more integration tests

Problem: incorrect codecov reporting (fixes #278)

---

.github/workflows/build.yml
.github/workflows/nix.yml

Solution:
- set the github access token

Problem: nix in CI trigger rate limit

---

.github/workflows/audit.yml
.github/workflows/build.yml
.github/workflows/buildwin.yml
.github/workflows/codecov.yml
.github/workflows/gosec.yml
.github/workflows/lint.yml
.github/workflows/nix.yml

Solution:
- upgrade github action scripts

Problem: github action use deprecated features

---

.github/workflows/release.yml

Problem: release workflow fail at checksum file names

---

app/state.go
x/nft/client/cli/tx.go

Closes: https://github.com/crypto-org-chain/chain-main/issues/872

Problem: filepath not cleaned from potential variable inclusion

---

app/sim_test.go

Problem: sim tests are fail due to missing chain id

---

.github/workflows/audit.yml
.github/workflows/build.yml
.github/workflows/buildwin.yml
.github/workflows/codecov.yml
.github/workflows/codeql-analysis.yml
.github/workflows/lint.yml

Solution: upgrade to Go 1.20.2

Problem: govulncheck fails

---

default.nix
flake.nix
nix/default.nix
nix/rocksdb.nix
scripts/release.sh

Solution:
- port the changes from cronos
- use static-linking in release for linux

Problem: static build on linux fails

---

flake.nix
nix/build_overlay.nix
nix/default.nix
nix/playtests-darwin.patch
nix/zstd.nix

Solution:
- vendor the zstd nix expression which has the fix

Problem: zstd build failed when cross-compilied on macos

---

nix/zstd.nix

Solution:
- apply the fix based on zstd nix expression in release-22.11

Problem: zstd build fail for mingw64 cross-compiling

---

default.nix
integration_tests/shell.nix
nix/default.nix

Solution:
- only build with `-cover` flag for integration test binary

Problem: released binaries contains -cover flag

---

CHANGELOG.md
go.mod
go.sum
gomod2nix.toml

Solution:
- update ibc-go to v5.2.1

Problem: fixes in ibc-go v5.2.1 are not included

---

nix/build_overlay.nix

Problem: go 1.20.4 is not used

---

CHANGELOG.md
default.nix

Problem: v4.2.5 is not released

---

CHANGELOG.md
default.nix
go.mod
go.sum
gomod2nix.toml

Solution:
- cherry-pick barberry fix in cosmos-sdk

Problem: barberry not patched

---

flake.nix
nix/bundle-win-exe.nix

Solution:
- adapt the pieces from cronos

Problem: windows bundle release script is not complete

---

CHANGELOG.md
default.nix

Problem: v4.2.7 is not released

---

CHANGELOG.md
go.mod
go.sum
gomod2nix.toml

Problem: cometbft dependency is not updated

---

go.mod
go.sum
gomod2nix.toml

Solution:
- update memiavl deps

Problem: memiavl don't support rollback

---

CHANGELOG.md
go.mod
go.sum
gomod2nix.toml

Problem: latest sdk and memiavl not integrated

---

nix/rocksdb.nix

This change should have been included in 4650fba17463114da3dd66c5d33365275199fa51

Problem: librocksdb has hardcoded rpath in cross-compiling

---

CHANGELOG.md
default.nix

Problem: v4.2.8 is not released

---

nix/hermes.nix
nix/sources.json

Problem: hermes v1.4.0 is not used in integration tests

---

.github/workflows/build.yml

Problem: minor security issue in github workflow

---

.github/workflows/build.yml

Problem: minor security issue in build-rocksdb workflow

---

.github/workflows/nix.yml

Problem: no space left on device in upgrade test

---

app/app.go
app/types.go
nix/build_overlay.nix

chore: fix some comments

---

.github/workflows/audit.yml
.github/workflows/build.yml
.github/workflows/buildwin.yml
.github/workflows/codecov.yml
.github/workflows/codeql-analysis.yml
.github/workflows/gosec.yml
.github/workflows/lint.yml
.github/workflows/nix.yml
integration_tests/test_upgrade.py

Problem: no cancel-in-progress in ci flow

---

CHANGELOG.md
integration_tests/test_ibc_extended.py
x/supply/keeper/keeper.go
x/supply/types/expected_keepers.go

Problem: negative coin amount error when query supply liquid of non BaseCoinUnit

---

CHANGELOG.md
integration_tests/test_ibc_extended.py
x/supply/keeper/keeper.go
x/supply/types/expected_keepers.go

Problem: negative coin amount error when query supply liquid of non BaseCoinUnit(backport: #1099)

---

.github/workflows/build.yml
.github/workflows/nix.yml
nix/default.nix
nix/hermes.nix
nix/sources.json

Solution:
- update upload-artifact to v4

Problem: github workflows out of date (backport #1108)

---

nix/testenv.nix

Solution:
- use preferWheels seems faster

Problem: test-env don't use prebuilt wheels

---

.github/workflows/build.yml

for more info:
https://github.com/crypto-org-chain/chain-main/actions/runs/13277412226/job/37069440029
https://github.com/octokit/request-action/issues/315

Problem: unable to resolve octokit action v2.0.0

---

.github/workflows/build.yml
go.mod
go.sum
gomod2nix.toml

Merge commit from fork

---

CHANGELOG.md
default.nix

Problem: 4.2.12 is not released

---

go.mod
go.sum
gomod2nix.toml

Problem: Merge commit from fork

---

CHANGELOG.md
default.nix
go.mod
go.sum
gomod2nix.toml
nix/solomachine.nix

Merge commit from fork.

---

go.mod
go.sum
gomod2nix.toml
nix/solomachine.nix

Problem: patch not compatible with current solomachine

---

CHANGELOG.md
app/upgrades.go
default.nix
integration_tests/cosmoscli.py
integration_tests/test_upgrade.py
integration_tests/upgrade-test.nix
nix/default.nix
nix/sources.json

Problem: Cronos New Golden Age not released

---

flake.lock
flake.nix
integration_tests/shell.nix
nix/build_overlay.nix
nix/solomachine.nix
nix/sources.json
pystarport/new-convert.sh

Solution:
- update nixpkgs to 24.11, it'll update default rust to 1.82

Problem: nixpkgs not up to date

---

flake.nix
integration_tests/shell.nix
nix/solomachine.nix

https://github.com/crypto-com/ibc-solo-machine/pull/107

Problem: latest solomachine not tested

---

CHANGELOG.md
default.nix
go.mod
go.sum
gomod2nix.toml

Problem: security patch not included

---

nix/bundle-win-exe.nix

Problem: windows release build fail

---

x/nft-transfer/simulation/genesis_test.go
x/nft/keeper/denom.go
x/nft/types/collection.go
x/nft/types/owners.go

fix some function names in comment

chore: fix some function names in comment

---

nix/default.nix
nix/sources.json

Solution:
- rename ibc-rs to hermes

Problem: hermes repo is split from ibc-rs

---

integration_tests/utils.py

chore: update utils.py

---

integration_tests/README.md
x/nft-transfer/client/cli/query.go
x/nft-transfer/types/keys.go
x/nft-transfer/types/trace_test.go

chore: fix some typos

---

.github/workflows/nix.yml
integration_tests/shell.nix
nix/default.nix

For more [info](https://github.com/crypto-org-chain/chain-main/pull/1144)

Problem: go 1.22 is deprecated in ci

---

.github/workflows/nix.yml

test with https://github.com/crypto-org-chain/chain-main/actions/runs/15135304605/job/42545596142?pr=1152

Problem: no debug files uploaded for fail test

---

CHANGELOG.md
cmd/chain-maind/opendb/opendb_rocksdb.go

set cache index/filters avoid memory leak

Problem: memory leak in archive node

---

doc/architecture/adr-004.md

chore: correct typos for var name

---

CHANGELOG.md
Makefile
run-local-chain.sh

fix: makefile + add run local chain script

---

.github/issue_labeler.yml
.github/pr_labeler.yml
.github/workflows/build.yml
.github/workflows/lint.yml
.github/workflows/nix.yml
.github/workflows/release.yml
pystarport/default.nix

ci: add issue labeler config

---

.github/workflows/build.yml
.github/workflows/lint.yml
.github/workflows/nix.yml
.github/workflows/release.yml
go.mod
go.sum
gomod2nix.toml

fix: error deleting legacy versions bug

---

Makefile
readme.md

chore: add docs for rocksdb compilation

---

proto/chainmain/nft_transfer/v1/query.proto

fix inconsistent struct name in comment

chore: fix inconsistent struct name in comment

---

.github/workflows/lint.yml
CHANGELOG.md

ci: use golangci-lint run --fix
