pystarport/poetry.lock
pystarport/pyproject.toml
pystarport/pystarport/cluster.py
pystarport/pystarport/utils.py

Solution:
- add api in pystarport to generate module account addresses
usage:
```
$ pystarport cli - module_address distribution
cro1jv65s3grqf6v6jl3dp4t6c9t9rk99cd8lyv94w
$ pystarport cli - balance `pystarport cli - module_address distribution`
529955
```
to see all the module account names:
```
$ pystarport cli - module_address --help
...
NAME
name of module account, values: fee_collector,mint,gov,distribution,bonded_tokens_pool,not_bonded_tokens_pool

Problem (fix #202): no api to list/query/monitor module accounts

---

.github/workflows/goreleaser.yml
.gitignore
.goreleaser.yml
Makefile

solution: use docker to cross-compile the binary with `cgo` enabled

Problem: (fix #196) current goreleaser config may build binaries without ledger support

---

.gitignore
pystarport/pystarport/cluster.py

* test ledger device manually on windows with the binary build by the goreleaser , it works fine.
* integration test can not run on windows for the following reason:
* nix does not support the windows platform
* supervisor does not work fine on windows in my test
* Currently, [WSL does not have USB pass-through access](https://github.com/microsoft/WSL/issues/5158), so can't use ledger device on WSL.
* integration test works fine on windows WSL 2, if get an error like `docker-credential-desktop.exe not installed or not available in PATH`,  see [here](https://github.com/docker/for-mac/issues/3785)
* can not expose the container's port outside using the host network mode on WSL 2, so change to container link mode.

Problem: (fix #135) hw wallet not tested on windows

---

integration_tests/utils.py
pystarport/poetry.lock
pystarport/pyproject.toml
pystarport/pystarport/cli.py
pystarport/pystarport/cluster.py

Solution:
- redirect node logs to file
- use multitail utility to watch the logs
> One can also use `multitail data/node*.log` cli utility to watch the logs with a better UI.

Problem: pystarport's log don't distinguish different nodes

---

.github/workflows/goreleaser.yml
.goreleaser.yml

Solution: updated to use github token + commented out brews, as it may need to be updated manually
before permissioning is figured out

Problem: goreleaser is using wrong Env for GitHub token (fixes #251)

---

integration_tests/test_ibc.py
integration_tests/utils.py
nix/sources.json
pystarport/pystarport/cli.py
pystarport/pystarport/cluster.py

Solution:
- start `relayer start` together with chain binaries
- send ibc-transfer transaction with chain binary

Problem (fix #283): ibc-transfer not directly tested with chain-maind

---

CONTRIBUTING.md
readme.md

Solution: 
- Redirected to the discord channel; 
- Updated the discord badge ![disc](https://user-images.githubusercontent.com/51898510/102072915-79a95600-3e3d-11eb-9d16-b3f716733e9c.png)
- Added descriptions to "6. Start a local Development Network and Node" and " 7. Send Your First Transaction"  .

Problem: (fix#290) community chat should point to discord instead of gitter going forward

---

default.nix
integration_tests/test_gov.py
integration_tests/test_upgrade.py
integration_tests/upgrade-test.nix
integration_tests/utils.py

Reason: the binary built for upgrade integration tests is pinned to an
old version
Solution:
- build current source code

Problem: upgrade test failed after migrated to cosmos-sdk rc5

---

scripts/chain-utils.nix

Solution:
- add explicit port number

Problem: cosmos-sdk state sync don't work without explicit port number in https

---

x/chainmain/client/cli/genaccounts.go

Solution: Add `memory` option in help text. Fixes #334.

Problem: memory is missing in keyring backend help comment

---

app/app.go
default.nix
go.mod
go.sum
nix/sources.json

Solution:
- updated the upgrade handler to what @lezzokafka put in the proposal
- updated SDK to a patched fork of v0.41 with the evidence / bech32 fix

Problem: upgrade for crossfire was not correct

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
doc/architecture/README.md
doc/architecture/adr-template.md

Solution: added templates for ADRs and updated the contribution guidelines
with more details

Problem: no higher-level contribution guidelines (fixes #386)

---

.gitmodules
CHANGELOG.md
default.nix
go.mod
go.sum

Solution: updated the dependencies to use 0.42.0 instead of the patched 0.41.4

Problem: chain-main doesn't use the upstream Cosmos SDK release

---

CHANGELOG.md
app/app.go
default.nix
go.mod
go.sum

Solution: updated the constructor
as per https://github.com/cosmos/cosmos-sdk/commit/3de375248759d57fb568b90d1bdb9a5ff9ef8a52

Problem: bank keeper isn't correctly initialized

---

nix/default.nix
nix/sources.json

Solution:
- upgrade nixpkgs to recent unstable version
- use builtin poetry2nix in nixpkgs

Problem: nixpkgs version don't use go 1.16

---

cmd/chain-maind/app/app.go

solution: remove the duplicate commands

Problem: duplicate commands(#421)

---

cmd/chain-maind/app/app.go
integration_tests/configs/default.yaml
integration_tests/test_basic.py
integration_tests/test_multisig.py
pystarport/pystarport/cluster.py
pystarport/pystarport/cosmoscli.py

solution: add `multisign-batch` in tx subcommand and integration test

Problem: multi-sign batch command is not exposed and tested (#422)

---

CHANGELOG.md
go.mod
go.sum
gomod2nix.toml

Solution: bumped the version to 0.42.4 which contains
the patched Tendermint 0.34.9 (with a security fix for the lite client)

Problem: Cosmos SDK not up to date

---

cmd/chain-maind/app/app.go

Solution: changed default timeout_commit value to 3 seconds. Fixes #486.
These are the new defaults:
```
timeout_propose = "3s"
timeout_propose_delta = "500ms"
timeout_prevote = "1s"
timeout_prevote_delta = "500ms"
timeout_precommit = "1s"
timeout_precommit_delta = "500ms"
timeout_commit = "3s"
```

Problem: too long default timeout_commit value

---

x/nft/types/validation.go

Solution: Modified error message clarifying that DenomID only accepts lowecase letters. Fixes #542.

Problem: DenomID in NFT module does not accept capital letters

---

app/app.go
default.nix

Solution:
- call SetStoreLoader to initialise nft module store

Problem: nft module store is not initialized after upgrade

---

default.nix

Solution: removed the argument from the call
(argument was removed from the function in ea92405d18902e0e325f7f623eb4458b88d643f9 )

Problem: nix function called with an unexpected argument (fixes #584)

---

integration_tests/poetry.lock
integration_tests/pyproject.toml
integration_tests/test_ibc.py
nix/default.nix
nix/sources.json

Solution: upgraded pystarport due to breaking changes in Hermes
and nixkpgs (as Rust 1.53+ tooling is needed to build 0.6 Hermes)

Problem: integration with Hermes 0.6 is not tested

---

CHANGELOG.md
app/app.go
go.mod
go.sum
gomod2nix.toml

Solution: upgraded SDK to v0.42.9 and added the capability module to beginblocker order,
as needed according to https://github.com/cosmos/cosmos-sdk/releases/tag/v0.42.9

Problem: random app hash mismatch after state sync or node restart in 2.1.1 pre-release binary

---

integration_tests/test_upgrade.py

Solution: increased the target height of the upgrade proposal.
(otherwise, it's more likely the node proposes some block before upgrade shutdown
and then failing with " CONSENSUS FAILURE!!! err="+2/3 committed an invalid block: wrong Block.Header.AppHash.  Expected ..., got ...")

Problem: test_manual_upgrade_all occasionally fails on master (fixes #619)

---

app/export.go
app/sim_test.go

Solution:
- updated simtest to include extra types for generation
- updated export to use AddressFromValidatorsKey for the validator address conversion

Problem: test-sim-after-import fails on master (fixes #620)

---

integration_tests/test_feegrant.py
integration_tests/utils.py

Solution:
Add following tests to test `tx feegrant grant` and `tx feegrant revoke`
- check whether granter pays transaction fee with no fee limit or grant expiry
- check transaction should fail when exceeding grant fee limit
- check transaction should fail after grant expiry date
- check whether granter pays transaction fee under period limit during each period
- check exceeding period limit should not affect the next period
- check transaction should fail if fee grant is revoked
Fix #614

test fee grant and revoke grant (Fix #614)

---

go.mod
go.sum
gomod2nix.toml

Solution: manually bumped + override to v0.34.12
(needed to force the replace, as there's no Cosmos SDK release yet)

Problem: latest tendermint release is not used

---

nix/default.nix
nix/sources.json

Solution: bumped the hermes dependency to 0.7
in nix integration tests

Problem: latest IBC relayer release is not tested

---

.github/workflows/build.yml
.github/workflows/buildwin.yml
.github/workflows/codecov.yml
.github/workflows/goreleaser.yml
CHANGELOG.md
Makefile
go.mod
go.sum
gomod2nix.toml
integration_tests/test_sign_offline.py

Solution: bumped SDK + upgraded Go to 1.17

Problem: latest v0.44 SDK is not used

---

CHANGELOG.md
go.mod
go.sum
gomod2nix.toml

Solution: bumped the ibc-go dependency to 1.1.0
and removed the forced SDK and Tendermint replacements
(as the versions should all be now aligned)

Problem: latest ibc-go 1.1.0 is not used

---

.github/workflows/nix.yml

Solution: removed the dockerhub push step, as the image
doesn't seem to be used

Problem: publishing pystarportImage to dockerhub fails (fixes #652)

---

nix/sources.json

Closes: #702
Solution:
- update to release-21.11

Problem: the version of nixpkgs is old

---

.gitignore

Solution: Add files and folders created by `pystarport` to `.gitignore`

Problem: Files and folders created by `pystarport` when running integration tests are not in `.gitignore`

---

integration_tests/test_feegrant.py
pystarport/convert.sh

Solution: Update tendermint version in `convert.sh`

Problem: `make-proto` and `nix-integration-test` checks out old version of tendermint

---

Makefile

Solution: Change simulation tests app location to `chain-main/v4/app`

Problem: Simulation tests does not point to correct location

---

default.nix
go.mod
go.sum
gomod2nix.toml

Solution: Remove manual version override from `go.mod` + update version to `4.0.0` in `default.nix`

Problem: Cosmos SDK v0.45.1 is still not used

---

app/app.go

Solution: Enable interchain accounts in `app.go` and add an upgrade handler

Problem: Interchain accounts are not enabled in `chain-main`

---

integration_tests/configs/ica.yaml
integration_tests/test_ica.py

Solution: Added integration tests

Problem: Missing integration tests for interchain accounts

---

x/icaauth/keeper/keeper.go
x/icaauth/keeper/msg_server_register_account.go

Solution: (Fix #736) Expose RegisterInterchainAccount method

Problem: RegisterInterchainAccount is not exposed in icaauth keeper

---

app/app.go

Solution: Added `x/authz` and `x/nft` messages to the list. Fixes #726.

Problem: List of `AllowMessages` for ICA is not finalized

---

app/sim_test.go
app/state.go

Solution: Vendored in `state.go` in `chain-main/app` so that it takes default genesis value from `app.ModuleBasic` instead of taking it from cosmos-sdk's simapp

Problem: Simulation tests fail after enabling ICA module

---

.github/workflows/audit.yml

Solution: Temporarily add it to list of `exclude-vulnerability`.
Note: It is already updated in `cosmos-sdk` and will release in v0.46.0.

Problem: Audit fails because of vulnerable go-ethereum dependency

---

.github/workflows/build.yml

Solution:
- grant enough permission

Problem: default permission for build.yml is not enough (fix #811)

---

integration_tests/test_byzantine.py

Solution: Assert either unbonding or unbonded status

Problem: Jailed validators can sometimes become unbonded before assert statement is executed in integration tests

---

.github/workflows/release.yml

Solution: Changed the release script to create testnet binaries

Problem: Release script does not create testnet binaries on `release/v4-croeseid` branch

---

go.mod
go.sum
gomod2nix.toml

Solution: Upgraded ibc-go to v4.0.0-rc2 and changed wasmd to different patched version.

Problem: ibc-go is not upgraded to v4.0.0-rc2

---

app/app.go

Solution: Enable fee middleware for ICA module

Problem: Fee middleware is not enabled for ICA module

---

go.mod
go.sum
gomod2nix.toml

Solution: Cherrypick `ibc-go` upgrade commit.

Problem: `release/v4-croeseid` branch is not up-to-date

---

app/app.go
integration_tests/configs/default.yaml
integration_tests/pyproject.toml
integration_tests/test_reward.py
integration_tests/test_upgrade.py

Solution: added a custom upgrade handler to raise
the min commission to 5% to all validators after the upgrade is executed

Problem: min commission is not set (fixes #843)

---

.github/workflows/nix.yml

Solution:
- add a job to upload binary cache for macos x86 automatically.

Problem: nix binary cache is not uploaded for macos

---

.github/workflows/build.yml
default.nix
flake.lock
flake.nix
integration_tests/shell.nix
nix/sources.json

Solution:
- build `updateScript` in nix expression.
- add workflow to check gomod2nix.toml up to date.
- update gomod2nix to upstream master branch.
Now, one should run `nix run .#update-gomod2nix` to update gomod2nix, rather than run `gomod2nix` directly, a direct run will always use go 1.17.
After https://github.com/nix-community/gomod2nix/pull/92 merged, we'll be able to use the builtin script, for now we'll use the custom one.

Problem: gomod2nix don't use the same golang version as project

---

.github/workflows/gosec.yml

Solution: updated the gh action permissions

Problem: gosec fails to upload analysis results

---

x/nft/types/keys.go
x/nft/types/keys_test.go

Solution: Fixed denomID and tokenID splitting logic when denom has `ibc`. Fixes #901.

Problem: `query nft owner` returns error when user has NFTs transferred over IBC

---

CHANGELOG.md
app/app.go
go.mod
go.sum
gomod2nix.toml
integration_tests/test_upgrade.py
integration_tests/upgrade-test.nix

Solution: added the missing staking messages and ICS721 to the allowlist, plus changed the ugprade plan name

Problem: missing ICA messages in the upgrade plan

---

app/export.go

Close: #920 
- Update logic return of `ExportAppStateAndValidators` function
- This is a small thing, but important for the logic code

update logic ExportAppStateAndValidators function

---

CHANGELOG.md
flake.lock
flake.nix
nix/default.nix
nix/sources.json

Solution:
- update nixpkgs to release-22.11
- manually update go src to 1.20.3
- prepare for v4.2.4 release

Problem: go 1.20.3 not used

---

CHANGELOG.md
app/app.go
app/config/config.go
app/config/toml.go
app/memiavl.go
cmd/chain-maind/app/app.go
go.mod
go.sum
gomod2nix.toml
integration_tests/configs/cosmovisor.jsonnet
integration_tests/configs/default.jsonnet
integration_tests/test_upgrade.py

Solution:
- integrate memiavl feature

Problem: memiavl is not integrated

---

app/app.go
go.mod
go.sum
gomod2nix.toml

Solution:
- fix in memiavl and update deps, see https://github.com/crypto-org-chain/cronos/pull/1088

Problem: memiavl result is different when replaying write-ahead-log

---

CHANGELOG.md
app/app.go

Solution:
- port the fix from sdk: https://github.com/cosmos/cosmos-sdk/pull/16639

Problem: halt-height is not deterministic

---

default.nix
nix/rocksdb.nix

Problem: librocksdb version is not updated

---

integration_tests/cosmoscli.py
integration_tests/test_gov.py

Problem: update icahost enabled is not tested

---

default.nix

Solution:
- fix the expression

Problem: fail to build in recent nixpkgs

---

app/app.go
app/docs/embed.go
app/docs/statik/init.go
go.mod
scripts/update-swagger-ui-statik.sh

Problem: statik bring big binary size diff

---

.github/workflows/build.yml

Problem: minor security issue in github workflow

---

app/docs/swagger_legacy.yaml
app/types.go
integration_tests/test_basic.py

chore: fix some comments

---

x/nft-transfer/client/cli/query.go
x/nft-transfer/keeper/relay.go
x/nft/keeper/nft.go

chore: remove repetitive words

---

SECURITY.md

This PR is to update the bug bounty link and remove the outdated Contact Us links.

Updating the Security Contact Us Details

---

CHANGELOG.md
app/app.go
app/upgrades.go

Problem: MsgModuleQuerySafe is not in allowed messages when upgrade

---

CHANGELOG.md
app/upgrades.go
app/upgrades_test.go
integration_tests/cosmoscli.py
integration_tests/test_gov.py
integration_tests/test_upgrade.py
integration_tests/utils.py

Problem: expedited related gov params are not adjusted

---

.github/workflows/audit.yml
.github/workflows/build.yml
.github/workflows/buildwin.yml
.github/workflows/codecov.yml
.github/workflows/codeql-analysis.yml
.github/workflows/gosec.yml
.github/workflows/lint.yml
.github/workflows/nix.yml
.github/workflows/release.yml
.github/workflows/semgrep.yml
.github/workflows/staticmajor.yml
CHANGELOG.md
go.mod
go.sum
gomod2nix.toml
integration_tests/install_solo_machine.nix

Problem: solomachine and ibc-go are outdated

---

.github/workflows/build.yml
integration_tests/install_solo_machine.nix

Solution:
- try persist-credentials: false

Problem: persist-credentials might leak github token unintentionally

---

.github/workflows/audit.yml
.github/workflows/build.yml
.github/workflows/buildwin.yml
.github/workflows/codecov.yml
.github/workflows/codeql-analysis.yml
.github/workflows/gosec.yml
.github/workflows/lint.yml
.github/workflows/nix.yml
.github/workflows/release.yml
.github/workflows/semgrep.yml
.github/workflows/staticmajor.yml
CHANGELOG.md
default.nix
go.mod
go.sum
gomod2nix.toml

for more [info](https://github.com/cosmos/cosmos-sdk/commit/ba7ac458c9f9b813a79890a8cc4786d536d3dd28)

Problem: security patch from cosmos sdk is not included

---

.github/workflows/release.yml
scripts/release.sh

Problem: aarch64-darwin is not supported

---

.github/workflows/build.yml
.github/workflows/nix.yml

Solution:
- update upload-artifact to v4

Problem: github workflows out of date
